import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./ui/globals.css";
import Header from "./ui/header/header";
import { ChakraProvider } from '@chakra-ui/react'

import { ClerkProvider } from '@clerk/nextjs'
import { ptBR } from "@clerk/localizations";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={ptBR}>
      <html lang="pt-br" className="">
        <body className={inter.className}>
          <ChakraProvider>
            <Header />
            {children}
          </ChakraProvider>
        </body>
      </html>
    </ClerkProvider>

  );
}
