import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./ui/globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import { ptBR } from "@clerk/localizations";
import { ClerkProvider } from "@clerk/nextjs";
import Hydrate from "./ui/components/hydrate";
import Header from "./ui/header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "E-commerce",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider localization={ptBR}>
			<html lang="pt-BR" className="">
				<body className={inter.className}>
					<Hydrate>
						<ChakraProvider>
							<Header />
							{children}
						</ChakraProvider>
					</Hydrate>
				</body>
			</html>
		</ClerkProvider>
	);
}
